before:
  hooks:
    - "go mod download"

builds:
  - flags:
    - -buildmode=exe
    env:
      - CGO_ENANLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w -X github.com/yandex-cloud/cq-source-yc/plugin.Version={{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: zip
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"