name: Release plugin to GitHub

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-deep: 0
      
      - name: Setup Go 1.x
        uses: actions/setup-go@v4
      
      - name: Install GoReleaser & publish
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}