name: "Unit tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unitests:
    name: Unit tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go mod download
      - run: go build ./...
      - name: Run tests
        run: go test -race ./...