name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Set up AWS
      run: |
        python -m pip install --upgrade pip
        pip install awscli

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      env:
        YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
        YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
        YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        YC_STORAGE_ACCESS_KEY: ${{ secrets.YC_SA_STATIC_KEY_ID }}
        YC_STORAGE_SECRET_KEY: ${{ secrets.YC_SA_STATIC_SECRET }}
      run: make test
    
