name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  postgres:
    strategy:
      matrix:
        dbversion: ['postgres:latest', 'postgres:12', 'postgres:11']
        go: ['1.15']
        platform: [ubuntu-latest] # can not run in macOS and Windows OS
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: ${{ matrix.dbversion }}
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Set up Python
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Set up
      run: |
        python -m pip install --upgrade pip
        pip install awscli

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      env:
        YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
        YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
        YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        YC_STORAGE_ACCESS_KEY: ${{ secrets.YC_SA_STATIC_KEY_ID }}
        YC_STORAGE_SECRET_KEY: ${{ secrets.YC_SA_STATIC_SECRET }}
      run: make test
    
